name: Format & Lint Code on PR Merge

on:
    workflow_run:
        workflows: ['Generate API Client on PR Merge']
        types:
            - completed

permissions:
    contents: write

jobs:
    format-and-lint:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: self-hosted
        steps:
            - name: set cache dirs
              run: |
                  echo "NPM_CONFIG_CACHE=$HOME/.cache/npm" >> $GITHUB_ENV
                  echo "UV_CACHE_DIR=$HOME/.cache/uv" >> $GITHUB_ENV

            - name: checkout
              uses: actions/checkout@v6
              with:
                  ref: stage

            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 'lts/*'
                  check-latest: true
                  cache: 'npm'
                  cache-dependency-path: |
                      package-lock.json
                      client/package-lock.json

            - name: install deps - base
              run: |
                  npm config ls
                  npm ci --ignore-scripts

            - name: install deps - client
              working-directory: client
              run: |
                  npm config ls
                  npm ci

            - name: setup uv
              uses: astral-sh/setup-uv@v7
              with:
                  working-directory: server
                  enable-cache: true
                  cache-dependency-glob: uv.lock

            - name: install deps - server
              working-directory: server
              run: uv sync

            - name: format & lint
              run: |
                  npm run format
                  npm run lint

            - name: commit & push
              run: |
                  if [[ -n "$(git status --porcelain)" ]]; then
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"

                    git add .
                    git status
                    git commit -m "chore: format & lint code after PR merge"
                    git status
                    git push
                  else
                    echo "No formatting changes to commit"
                  fi
