name: Generate API Client on PR Merge

on:
    pull_request:
        branches:
            - stage
        types:
            - closed

permissions:
    contents: write

jobs:
    generate-api:
        if: github.event.pull_request.merged == true
        runs-on: self-hosted
        environment: stage
        steps:
            - name: set cache dirs
              run: |
                  echo "NPM_CONFIG_CACHE=$HOME/.cache/npm" >> $GITHUB_ENV
                  echo "UV_CACHE_DIR=$HOME/.cache/uv" >> $GITHUB_ENV

            - name: checkout
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.event.pull_request.base.ref }}

            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 'lts/*'
                  cache: 'npm'
                  cache-dependency-path: client/package-lock.json

            - name: install deps - client
              working-directory: client
              run: |
                  npm config ls
                  npm ci

            - name: setup uv
              uses: astral-sh/setup-uv@v7
              with:
                  working-directory: server
                  enable-cache: true
                  cache-dependency-glob: uv.lock

            - name: install deps - server
              working-directory: server
              run: uv sync

            - name: generate api client
              working-directory: scripts
              run: ./generate_api.sh -f

            - name: set up docker buildx
              uses: docker/setup-buildx-action@v3

            - name: build client image
              uses: docker/build-push-action@v6
              with:
                  context: client
                  target: build
                  build-args: |
                      VITE_ENV=ci
                      VITE_IMAGE_TAG=ci-tag
                      VITE_API_URL=https://api.example.com
                  cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/cache/${{ vars.PROJECT }}-${{ vars.ENV }}-client:buildkit
                  cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/cache/${{ vars.PROJECT }}-${{ vars.ENV }}-client:buildkit,mode=max

            - name: commit & push
              run: |
                  if [[ -n "$(git status --porcelain)" ]]; then
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"

                    git add .
                    git status
                    git commit -m "chore: update generated API client after PR merge"
                    git status
                    git push
                  else
                    echo "No changes to commit"
                  fi
