name: Merge main into stage on PR Merge

on:
    pull_request:
        branches:
            - main
        types:
            - closed

permissions:
    contents: write

jobs:
    merge-main-into-stage:
        if: github.event.pull_request.merged == true
        runs-on: self-hosted
        steps:
            - name: checkout stage
              uses: actions/checkout@v6
              with:
                  ref: stage

            - name: merge main into stage
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

                  git fetch origin main stage
                  git checkout stage
                  git merge --no-edit origin/main
                  git push origin stage
