name: Run Server Tests

on:
    workflow_dispatch:
    pull_request_target:
        branches:
            - stage
            - main

permissions:
    contents: none

jobs:
    test-server:
        runs-on: self-hosted
        environment: test
        steps:
            - name: set cache dir
              run: |
                  echo "UV_CACHE_DIR=$HOME/.cache/uv" >> $GITHUB_ENV

            - name: checkout
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.event.pull_request.head.sha || github.ref_name }}

            - name: setup uv
              uses: astral-sh/setup-uv@v7
              with:
                  working-directory: server
                  enable-cache: true
                  cache-dependency-glob: uv.lock

            - name: install
              working-directory: server
              run: uv sync

            - name: create .env
              working-directory: config/env
              run: |
                  echo "ENV=test" >> .env
                  echo "LOG_LEVEL=debug" >> .env
                  echo "CLIENT_URL=" >> .env

                  echo "ADMIN__USERNAME=${{ secrets.ADMIN__USERNAME }}" >> .env
                  echo "ADMIN__EMAIL=${{ secrets.ADMIN__EMAIL }}" >> .env
                  echo "ADMIN__FIRST_NAME=${{ secrets.ADMIN__FIRST_NAME }}" >> .env
                  echo "ADMIN__LAST_NAME=${{ secrets.ADMIN__LAST_NAME }}" >> .env
                  echo "ADMIN__PASSWORD=${{ secrets.ADMIN__PASSWORD }}" >> .env

                  echo "JWT__SECRET_KEY=${{ secrets.JWT__SECRET_KEY }}" >> .env
                  echo "JWT__ALGORITHM=${{ secrets.JWT__ALGORITHM }}" >> .env
                  echo "JWT__ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.JWT__ACCESS_TOKEN_EXPIRE_MINUTES }}" >> .env
                  echo "JWT__REFRESH_TOKEN_EXPIRE_DAYS=${{ secrets.JWT__REFRESH_TOKEN_EXPIRE_DAYS }}" >> .env

                  echo "DB__HOST=" >> .env
                  echo "DB__PORT=0" >> .env
                  echo "DB__NAME=" >> .env
                  echo "DB__USER=" >> .env
                  echo "DB__PASSWORD=" >> .env

                  echo "EMAIL__BACKEND=console" >> .env

                  echo "GH__BACKEND=console" >> .env

            - name: run type checks
              working-directory: server
              run: make check

            - name: run tests
              working-directory: server
              run: make test
