name: Run Server Tests

on:
    workflow_dispatch:
    pull_request_target:
        branches:
            - stage
            - main

permissions:
    contents: none

jobs:
    test-server:
        runs-on: self-hosted
        environment: ${{ github.base_ref == 'main' && 'prod' || github.base_ref || github.ref_name }}
        steps:
            - name: checkout
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.event.pull_request.head.sha || github.ref_name }}

            - name: setup uv
              uses: astral-sh/setup-uv@v7
              with:
                  working-directory: server
                  enable-cache: true
                  cache-python: true

            - name: install
              working-directory: server
              run: uv sync

            - name: run tests
              working-directory: server
              run: make test

            - name: remove cache folder
              if: always()
              working-directory: server
              run: rm -rf .uv
